bt2/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('auth/', views.auth, name='auth'),
    path('accounts/', include('allauth.urls')),
    path('home/', views.home, name='home'),
    path('reserve/', views.reserve, name='reserve'),
    path('reserve_done/', views.reserve_done, name='reserve_done'),
    path('view_reservations/', views.view_reservations, name='view_reservations'),
    path('logout/', views.logout_view, name='logout'),
    path('delete/<int:reservation_id>/', views.delete_reservation, name='delete_reservation'),
    path('edit/<int:reservation_id>/', views.edit_reservation, name='edit_reservation'),
    path('edit_reservation_done/', views.edit_reservation_done, name='edit_reservation_done'),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

reservas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class TrainingType(models.Model):
    name = models.CharField(max_length=50, verbose_name="Nombre")
    description = models.CharField(max_length=50, verbose_name="Descripción")
    image = models.ImageField(upload_to='training_type_images/', null=True, blank=True, verbose_name="Imagen")

    class Meta:
        verbose_name = "Tipo de entrenamiento"
        verbose_name_plural = "Tipos de entrenamiento"
        ordering = ['name']

    def __str__(self):
        return self.name

class TrainingReservation(models.Model):
    date = models.DateField(verbose_name="Fecha", default=timezone.now)
    time = models.TimeField(verbose_name="Hora del entrenamiento")
    location = models.CharField(max_length=50, verbose_name="Dirección lugar de entrenamiento")
    training_type = models.ForeignKey(TrainingType, on_delete=models.SET_NULL, null=True)
    phone = models.CharField(max_length=20, verbose_name="Celular del cliente")
    notes = models.CharField(max_length=250, verbose_name="Comentarios adicionales", blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Usuario", default=None)
    google_event_id = models.CharField(max_length=255, null=True, blank=True)
    completed = models.BooleanField(default=False, verbose_name="Completado")

    class Meta:
        verbose_name = "Reserva de entrenamiento"
        verbose_name_plural = "Reservas de entrenamiento"
        ordering = ['date']

    def __str__(self):
        return f'Cita para {self.user.username} el {self.date} a las {self.time.strftime("%H:%M")}'

templates/reserve/edit_reservation.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Modificar Reserva
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/reserve/reserve.css'%}">
{% endblock %}

{% block enlace_logo %}
<a href='/home/'>
{% endblock %}

{% block enlace_logo_mobile %}
<a href='/home/'>
{% endblock %}


{% block extra_navbar %}
<a href="/logout/" class="btn btn-outline-light"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
<path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z" />
<path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z" />
</svg><span class="logout-text"> Cerrar Sesión</span></a>
{% endblock %}

{% block content %}
<div class="container">
    <img src="{% static 'image/unsplash2.jpg' %}" class="unsplash">
    <img src="{% static 'image/pesa.png' %}" class="pesa">
    <img src="{% static 'image/balon-m.png' %}" class="balon-m">
    <div class="form-content">
        <h2 class="form-title">MODIFICAR RESERVA</h2>

        <form method="GET" action="{% url 'edit_reservation' reserva.id %}" id="date-selection-form">
            <div class="form-group">
                <label for="id_date">Selecciona la fecha:</label>
                <input type="date" name="date" required id="id_date" value="{{ form.date.value|date:'Y-m-d' }}">
            </div>
        </form>

        <hr>

        <form method="POST" action="{% url 'edit_reservation' reserva.id %}" class="reserve-form">
            {% csrf_token %}

            <input type="hidden" name="date" value="{{ selected_date }}">

            <div class="form-group">
                <label for="id_time">Elige una hora disponible:</label>
                {{ form.time }}
            </div>

            <div class="form-group">
                <label for="id_location">Dirección del entrenamiento:</label>
                {{ form.location }}
            </div>

            <div class="form-group">
                <label for="id_phone">Celular del cliente:</label>
                {{ form.phone }}
            </div>

            <div class="form-group">
                <label for="id_training_type">Tipo de entrenamiento:</label>
                {{ form.training_type }}
            </div>

            <div class="form-group">
                <label for="id_notes">Comentarios adicionales:</label>
                {{ form.notes }}
            </div>

            <div class="form-group">
                <button type="submit">Guardar Cambios</button>
            </div>
        </form>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const dateInput = document.getElementById('id_date');
        if (dateInput) {
            dateInput.addEventListener('change', function() {
                document.getElementById('date-selection-form').submit();
            });
        }
    });
</script>
{% endblock %}

templates/reserve/edit_reservation_done.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Reserva Completada
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/reserve/reserve_done.css' %}">
{% endblock %}

{% block enlace_logo %}
<a href='/home/'>
{% endblock %}

{% block enlace_logo_mobile %}
<a href='/home/'>
{% endblock %}a

{% block extra_navbar %}
<a href="/logout/" class="btn btn-outline-light logout-btn"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
    <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
  </svg><span class="logout-text"> Cerrar Sesión</span></a>
{% endblock %}

{% block content %}
<picture class="background-container">
  <source srcset="{% static 'image/background_reserve_done4.png' %}" media="(width < 565px)" class="background_reserve_mobile">
  <img src="{% static 'image/background_reserve_done3.png' %}" class="background_reserve_done">
</picture>

<div class="reserve_done-container">
  <div class="header-container">
    <span class="header">¡FELICITACIONES TU RESERVA SE HA MODIFICADO!</span>
    <span class="confirmation-text">Tu sesión de entrenamiento personalizado ha sido modificada con éxito. Pronto, un miembro de nuestro equipo se pondrá en contacto contigo. Mientras tanto, puedes revisar o seguir modificando todos los detalles de tus citas en cualquier momento haciendo click en el siguiente botón.</span>
   <a href="/view_reservations/" class="btn-view_reservation">CONSULTAR ENTRENAMIENTOS</a>
  </div>
  <div class="bottom-row">
    <div class="btn-home-container">
      <span class="header-home">Explora más opciones volviendo a nuestro menú.</span>
      <a href="/home/" class="btn-home">VOLVER AL MENÚ PRINCIPAL</a>
    </div>
    <div class="btn-reserve-container">
      <span class="header-reserve">Mantén tu motivación y agenda el próximo entrenamiento.</span>
      <a href="/reserve/" class="btn-reserve">RESERVAR OTRO ENTRENAMIENTO</a>
    </div>
  </div>
</div>
{% endblock %}

templates/reserve/reserve.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Reservar Entrenamiento
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/reserve/reserve.css'%}">
{% endblock %}

{% block enlace_logo %}
<a href='/home/'>
{% endblock %}

{% block enlace_logo_mobile %}
<a href='/home/'>
{% endblock %}


  {% block extra_navbar %}
  <a href="/logout/" class="btn btn-outline-light logout-btn"><svg xmlns="http://www.w3.org/2000/svg"
      width="20" height="20" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
      <path fill-rule="evenodd"
        d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z" />
      <path fill-rule="evenodd"
        d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z" />
    </svg><span class="logout-text"> Cerrar Sesión</span></a>
  {% endblock %}

  {% block content %}
  <div class="container">
    <img src="{% static 'image/unsplash2.jpg' %}" class="unsplash">
    <img src="{% static 'image/pesa.png' %}" class="pesa">
    <img src="{% static 'image/balon-m.png' %}" class="balon-m">
    <div class="form-content">
        <h3 class="form-title">RESERVA TU ENTRENAMIENTO</h3>

        <form method="GET" action="{% url 'reserve' %}" id="date-selection-form">
        <div class="form-group">
            <label for="id_date">Selecciona la fecha:</label>
            <input type="date" name="date" required id="id_date" value="{{ selected_date }}">
        </div>
    </form>

    <hr class="linea">

    <form method="POST" class="reserve-form">
        {% csrf_token %}
        <input type="hidden" name="date" value="{{ selected_date }}">

        <div class="form-group">
            <label for="id_time">Elige una hora disponible:</label>
            {{ form.time }}
        </div>

        <div class="form-group">
            <label for="id_location">Dirección del entrenamiento:</label>
            {{ form.location }}
        </div>

        <div class="form-group">
            <label for="id_phone">Celular del cliente:</label>
            {{ form.phone }}
        </div>

        <div class="form-group">
            <label for="id_training_type">Tipo de entrenamiento:</label>
            {{ form.training_type }}
        </div>

        <div class="form-group">
            <label for="id_notes">Comentarios adicionales:</label>
            {{ form.notes }}
        </div>

        <div class="form-group">
            <button type="submit">¡RESERVAR YA!</button>
        </div>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const dateInput = document.getElementById('id_date');
        if (dateInput) {
            dateInput.addEventListener('change', function() {
                document.getElementById('date-selection-form').submit();
            });
        }
    });
</script>
  {% endblock %}

templates/reserve/reserve_done.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Reserva Completada
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/reserve/reserve_done.css' %}">
{% endblock %}

{% block enlace_logo %}
<a href='/home/'>
{% endblock %}

{% block enlace_logo_mobile %}
<a href='/home/'>
{% endblock %}


{% block extra_navbar %}
<a href="/logout/" class="btn btn-outline-light logout-btn"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
    <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
  </svg><span class="logout-text"> Cerrar Sesión</span></a>
{% endblock %}

{% block content %}
<picture class="background-container">
  <source srcset="{% static 'image/background_reserve_done4.png' %}" media="(width < 565px)" class="background_reserve_mobile">
  <img src="{% static 'image/background_reserve_done3.png' %}" class="background_reserve_done">
</picture>

<div class="reserve_done-container">
  <div class="header-container">
    <span class="header">¡FELICITACIONES SE HA REALIZADO TU RESERVA!</span>
    <span class="confirmation-text">Tu sesión de entrenamiento personalizado ha sido agendada con éxito. Pronto, un miembro de nuestro equipo se pondrá en contacto contigo. Mientras tanto, puedes revisar o modificar todos los detalles de tus citas en cualquier momento haciendo click en el siguiente botón.</span>
    <a href="/view_reservations/" class="btn-view_reservation">CONSULTAR ENTRENAMIENTOS</a>
  </div>
  <div class="bottom-row">
    <div class="btn-home-container">
      <span class="header-home">Explora más opciones volviendo a nuestro menú.</span>
      <a href="/home/" class="btn-home">VOLVER AL MENÚ PRINCIPAL</a>
    </div>
    <div class="btn-reserve-container">
      <span class="header-reserve">Mantén tu motivación y agenda el próximo entrenamiento.</span>
      <a href="/reserve/" class="btn-reserve">RESERVAR OTRO ENTRENAMIENTO</a>
    </div>
  </div>
</div>
{% endblock %}

templates/reserve/view_reservations.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Mis Reservas
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/reserve/view_reservations.css'%}">
{% endblock %}

{% block enlace_logo %}
<a href='/home/'>
{% endblock %}

{% block enlace_logo_mobile %}
<a href='/home/'>
{% endblock %}

{% block extra_navbar %}
<a href="/logout/" class="btn btn-outline-light logout-btn"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
    <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
  </svg><span class="logout-text"> Cerrar Sesión</span></a>
{% endblock %}

{% block content %}
<div class="container">
    {% if reservas %}
    <span class="header">MIS RESERVAS DE ENTRENAMIENTO </span>
        <div class="reservas-grid">
            {% for reserva in reservas %}
                <div class="reserva-card">
                    <div class="reserva-image-container">
                        {% if reserva.training_type and reserva.training_type.image %}
                                <img src="{{ reserva.training_type.image.url }}" alt="{{ reserva.training_type.name }}" class="training-type-image">
                        {% endif %}
                    </div>
                    <p><strong>Fecha:</strong> {{ reserva.date|date:"d/m/Y" }}</p>
                    <p><strong>Hora:</strong> {{ reserva.time|time:"h:i A" }}</p>
                    <p><strong>Lugar:</strong> {{ reserva.location }}</p>
                    <p>
                        <strong><span class="card-text">Tipo de </span>Entreno:</strong>
                        {% if reserva.training_type %}
                            {{ reserva.training_type.name }}
                        {% else %}
                          Sin especificar
                        {% endif %}
                    </p>
                    <div class="button-container">
                        <button type="button" class="custom-btn" data-reservation-id="{{ reserva.id }}">Opciones</button>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
    <span class="header2">MIS RESERVAS DE ENTRENAMIENTO </span>
        <div class="no-reservations">
            <img src="{% static 'image/balon-m.png' %}" class="balon-m">
            <img src="{% static 'image/pesa.png' %}" class="pesa">
            <img src="{% static 'image/golty.png' %}" class="golty">
            <img src="{% static 'image/basquet.png' %}" class="basquet">
            <div class="no-reservations-content">
                <p class="header-no-reservations">No tienes ninguna reserva de entrenamiento en este momento.</p>
                <a href="/reserve/" class="btn-reserve">¡Haz una reserva ahora!</a>
            </div>
        </div>
    {% endif %}
</div>

<div class="modal-overlay" id="options-modal">
    <div class="modal-content">
        <span class="modal-close">&times;</span>
        <h3>Opciones de Reserva</h3>
        <a href="#" id="edit-link" class="modal-button edit">Modificar Reserva</a>
        <form action="#" method="POST" id="delete-form">
            {% csrf_token %}
            <button type="submit" class="modal-button delete">Eliminar Reserva</button>
        </form>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'js/view_reservations.js' %}"></script>
{% endblock %}